name: Unit Tests in Docker

on:
  pull_request:
    branches:
      - main

jobs:
  setup-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Docker Image
        run: docker build --tag "test:0" .

      - name: Enter into image and run tests
        run: |-
          image_id=$(docker images test --format "{{.ID}}")
          docker run -t -d $image_id
          ps=$(docker ps --format "{{.ID}}")
          docker exec $ps sh -c "pip3 install pytest && python3 -m pytest -sv"

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # - name: Install System dependencies
      #   run: |
      #     sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run Pytest
        run: |
          python3 -m pytest -sv